# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Package ES Standard Build'
  
variables:
- group: 'Canaveral_ADO_Variable'
- name: solution
  value: '**/reliability-on-demand.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: clientAppDir
  value: 'reliability-on-demand\ClientApp'

steps:

- checkout: self
  clean: true
  submodules: true
  persistCredentials: true

- task: NuGetToolInstaller@1

# Avoiding ambiguous reference for NuGet
- task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(clientAppDir)'
  displayName: 'npm install on ClientApp'

# UNCOMMENT TO RUN REACT TESTS
# - task: Npm@1
#   displayName: 'npm test'
#   inputs:
#     command: 'custom'
#     workingDir: '$(clientAppDir)'
#     customCommand: 'test'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/test-report.xml'
#     failTaskOnFailedTests: true

- template: ./canaveralBuild.yml
  parameters:
    configuration: 'Release'
    fakeDeployment: false
    targets: 'Deploy'
    userName: $(BuildUserName)
    userPassword: $(BuildUserPassword)
    clientId: $(DeploymentClientId)
    clientSecret: $(DeploymentClientSecret)
