// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SampleConfig {
    ConfigID:       string;
    CreationDate:   string;
    LastCacheDate:  string;
    ExpiryDate:     string;
    ConfigName:     string;
    OwnerContact:   string;
    OwnerTeam:      string;
    CacheFrequency: number;
}

export interface ConfigInquiry{
    TeamID: number;
}

export interface TeamConfig {
    TeamID:                string;
    OwnerContact:          string;
    OwnerTeamFriendlyName: string;
    OwnerTriageAlias:      string;
}

export interface StudyConfig {
    StudyID:               string;
    StudyName:             string;
    LastRefreshDate:       Date;
    LastModifiedDate:      Date;
    CacheFrequency:        number;
    Expiry:                Date;
    TeamID:                number;
    ObservationWindowDays: number;
}

