// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface FailureConfig {
  StudyConfigID: number
  Verticals: string[]
  PivotSourceSubType: string
  Pivots: PivotTable[]
}

export interface Vertical {
  VerticalName: string
  PivotSourceSubType: string
}

export interface PivotType {
  PivotID: number
  IsSelectPivot: boolean
  IsKeyPivot: boolean
  IsApportionPivot: boolean
  IsApportionJoinPivot: boolean
  PivotScopeID: number
  FilterExpression: string
  UIInputDataType: string
  PivotKey: string
}

export interface Pivot extends PivotType {
  PivotSourceColumnName: string
}

export interface PivotTable extends PivotType {
  FilterExpressionOperator: string
  IsScopeFilter: boolean
  PivotName: string
}

export interface SmapSQL {
  IsSelectColumn: boolean
  IsKeyColumn: boolean
  IsApportionColumn: boolean
  IsApportionJoinColumn: boolean
  PivotScopeID: number
  PivotKey: string
  scope: Filter[]
}

export interface PivotSQLResult {
  PivotSourceColumnName: string
  PivotID: number
  UIInputDataType: string
  PivotKey: string
  smap: SmapSQL[]
}

export interface Filter {
  PivotScopeValue: string
  PivotScopeOperator: string
}

export interface FilterExpTable {
  RelationalOperator: string
  PivotName: string
  Operator: string
  PivotValue: string
  PivotID: number
  PivotScopeID: number
  UIInputDataType: string
  PivotKey: string
}

export interface PivotScopeFilter {
  PivotID: number
  FilterExpression: string
  RelationalOperator: string
  PivotKey: string
}
