// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface FailureConfig {
    StudyID: number;
    PivotSourceSubType: string;
    Pivots: PivotTable[];
}


export interface Vertical {
    VerticalName: string;
    PivotSourceSubType: string;
}

export interface Pivot {
    PivotSourceColumnName: string;
    PivotID: number;
    IsSelectPivot: boolean;
    IsKeyPivot: boolean;
    IsApportionPivot: boolean;
    IsApportionJoinPivot: boolean;
    PivotScopeID: number;
    FilterExpression: string;
}

export interface Pair {
    key: string,
    text: string
}

export interface PivotTable {
    PivotID: number;
    PivotName: string;
    IsSelectPivot: boolean;
    IsKeyPivot: boolean;
    IsApportionPivot: boolean;
    IsApportionJoinPivot: boolean;
    IsScopeFilter: boolean;
    PivotScopeID: number;
    FilterExpression: string;
    FilterExpressionOperator: string;
}

export interface SmapSQL {
    IsSelectColumn: boolean;
    IsKeyColumn: boolean;
    IsApportionColumn: boolean;
    IsApportionJoinColumn: boolean;
    PivotScopeID: number;
    scope: Filter[];
}

export interface PivotSQLResult {
    PivotSourceColumnName: string;
    PivotID: number;
    smap: SmapSQL[];
}

export interface Filter {
    PivotScopeValue: string;
    PivotScopeOperator: string;
}



